import type { SeedEntry } from './types';

/**
 * The 56 plants of docs/startkatalog.md as written there.
 * Neighbour lists keep the short forms; `resolve.ts` expands them.
 * IDs are fixed forever: plantings and overrides reference them.
 */
export const seedEntries: readonly SeedEntry[] = [
  {
    id: '01M49THV00SZ6Q8R32BYJM5P2S',
    name: 'Aubergine',
    category: 'GEMUESE',
    family: 'Nachtschattengewächse',
    feeder: 'STARK',
    spacingInRowCm: 40,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: [],
    bad: [],
    color: '#5b2a6e',
    icon: 'aubergine',
  },
  {
    id: '01M49THV00C1R6NEETK1CN1VBN',
    name: 'Blumenkohl',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'STARK',
    spacingInRowCm: 60,
    rowSpacingCm: 60,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 14 },
    good: { like: 'Brokkoli' },
    bad: { like: 'Brokkoli' },
    color: '#e8e0c4',
    icon: 'blumenkohl',
  },
  {
    id: '01M49THV00NFVX46FHMDBVTEXW',
    name: 'Brokkoli',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'STARK',
    spacingInRowCm: 50,
    rowSpacingCm: 50,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 12 },
    good: [
      'Tomate',
      'Bohnen',
      'Spinat',
      'Sellerie',
      'Kopfsalat',
      'Pflücksalat',
      'Salatgurke',
      'Radieschen',
      'Rettich',
      'Mangold',
      'Lauch',
      'Erbse',
      'Endivie',
      'Rhabarber',
    ],
    bad: ['andere Kohlarten', 'Zwiebel', 'Knoblauch', 'Kartoffel', 'Erdbeere'],
    color: '#2f6b3a',
    icon: 'brokkoli',
  },
  {
    id: '01M49THV00F0M4385NH7KDBCRV',
    name: 'Buschbohne',
    category: 'GEMUESE',
    family: 'Hülsenfrüchtler',
    feeder: 'SCHWACH',
    spacingInRowCm: 7,
    rowSpacingCm: 45,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 12 },
    good: [
      'Tomate',
      'Sellerie',
      'Radieschen',
      'Rettich',
      'Rote Bete',
      'Pflücksalat',
      'Mangold',
      'Salatgurke',
      'Kopfsalat',
      'Kohlrabi',
      'Kohl',
      'Kartoffel',
      'Rhabarber',
    ],
    bad: ['Zwiebel', 'Lauch', 'Knoblauch', 'Fenchel', 'Erbse'],
    color: '#6aa84f',
    icon: 'buschbohne',
  },
  {
    id: '01M49THV00EMB0XV85D9JZZJWR',
    name: 'Chili',
    category: 'GEMUESE',
    family: 'Nachtschattengewächse',
    feeder: 'STARK',
    spacingInRowCm: 40,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 20 },
    good: { like: 'Paprika' },
    bad: { like: 'Paprika' },
    color: '#c0392b',
    icon: 'chili',
  },
  {
    id: '01M49THV005MCER99GXKQZ4GSG',
    name: 'Chinakohl',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 30,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 10 },
    good: [],
    bad: [],
    color: '#c9dd94',
    icon: 'chinakohl',
  },
  {
    id: '01M49THV00C22V58FGQWDYNWVC',
    name: 'Endivie',
    category: 'GEMUESE',
    family: 'Korbblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 30,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 12 },
    good: ['Stangenbohne', 'Lauch', 'Kohl', 'Fenchel'],
    bad: ['Tomate', 'Buschbohne', 'Paprika', 'Kohlrabi'],
    color: '#9fc46a',
    icon: 'endivie',
  },
  {
    id: '01M49THV00013Z500A4NCK9WHY',
    name: 'Erbse',
    category: 'GEMUESE',
    family: 'Hülsenfrüchtler',
    feeder: 'SCHWACH',
    spacingInRowCm: 4,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 12 },
    good: ['Radieschen', 'Rettich', 'Kopfsalat', 'Kohl', 'Kohlrabi', 'Fenchel', 'Dill', 'Möhre'],
    bad: ['Tomate', 'Bohnen', 'Lauch', 'Knoblauch', 'Kartoffel'],
    color: '#7cb342',
    icon: 'erbse',
  },
  {
    id: '01M49THV00KTQVQ6WFGGKKKRY8',
    name: 'Feldsalat',
    category: 'GEMUESE',
    family: 'Baldriangewächse',
    feeder: 'SCHWACH',
    spacingInRowCm: 2,
    rowSpacingCm: 15,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 14 },
    good: [],
    bad: [],
    color: '#4f8a3c',
    icon: 'feldsalat',
  },
  {
    id: '01M49THV000YZENWMVH5151H76',
    name: 'Fenchel',
    category: 'GEMUESE',
    family: 'Doldenblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 20,
    rowSpacingCm: 45,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 12 },
    good: ['Endivie', 'Radicchio', 'Salbei', 'Pflücksalat', 'Kopfsalat', 'Salatgurke', 'Erbse'],
    bad: ['Bohnen', 'Tomate'],
    color: '#d4e2a6',
    icon: 'fenchel',
  },
  {
    id: '01M49THV00HV7YXZYWZ79KYHYS',
    name: 'Frühlingszwiebel',
    category: 'GEMUESE',
    family: 'Lauchgewächse',
    feeder: 'SCHWACH',
    spacingInRowCm: 3,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 10 },
    good: { like: 'Zwiebel' },
    bad: { like: 'Zwiebel' },
    color: '#8bc34a',
    icon: 'fruehlingszwiebel',
  },
  {
    id: '01M49THV00A6TVTS7JDM60G9YY',
    name: 'Grünkohl',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'STARK',
    spacingInRowCm: 50,
    rowSpacingCm: 50,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 30 },
    good: { like: 'Brokkoli' },
    bad: { like: 'Brokkoli' },
    color: '#1f5e3a',
    icon: 'gruenkohl',
  },
  {
    id: '01M49THV00ZXD963BV15Z5DW76',
    name: 'Kartoffel',
    category: 'GEMUESE',
    family: 'Nachtschattengewächse',
    feeder: 'STARK',
    spacingInRowCm: 30,
    rowSpacingCm: 60,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: ['Spinat', 'Pfefferminze', 'Kohlrabi', 'Dill', 'Buschbohne'],
    bad: ['Tomate', 'Sellerie', 'Erbse', 'Rote Bete', 'Kohl'],
    color: '#c8a165',
    icon: 'kartoffel',
  },
  {
    id: '01M49THV00SMEJ58VP36QRVY7B',
    name: 'Knoblauch',
    category: 'GEMUESE',
    family: 'Lauchgewächse',
    feeder: 'SCHWACH',
    spacingInRowCm: 15,
    rowSpacingCm: 20,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 38 },
    good: ['Tomate', 'Rote Bete', 'Salatgurke', 'Möhre', 'Erdbeere'],
    bad: ['Bohnen', 'Erbse', 'Kohl'],
    color: '#ede4d3',
    icon: 'knoblauch',
  },
  {
    id: '01M49THV00GZZ25SFHWVHG6CXN',
    name: 'Knollensellerie',
    category: 'GEMUESE',
    family: 'Doldenblütler',
    feeder: 'STARK',
    spacingInRowCm: 40,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 22 },
    good: [
      'Tomate',
      'Stangenbohne',
      'Spinat',
      'Lauch',
      'Kopfsalat',
      'Kohlrabi',
      'Kohl',
      'Salatgurke',
      'Buschbohne',
    ],
    bad: ['Zuckermais', 'Kartoffel'],
    color: '#cdbf91',
    icon: 'knollensellerie',
  },
  {
    id: '01M49THV007TNRTCQDEDDW9N6D',
    name: 'Kohlrabi',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 25,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 9 },
    good: [
      'Tomate',
      'Bohnen',
      'Spinat',
      'Sellerie',
      'Lauch',
      'Kartoffel',
      'Erbse',
      'Schwarzwurzel',
      'Rote Bete',
      'Radieschen',
      'Rettich',
      'Kopfsalat',
    ],
    bad: [],
    color: '#a8c97f',
    icon: 'kohlrabi',
  },
  {
    id: '01M49THV00RK9E9PC83NEE87CJ',
    name: 'Kopfsalat',
    category: 'GEMUESE',
    family: 'Korbblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 25,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 8 },
    good: [
      'Zwiebel',
      'Endivie',
      'Radicchio',
      'Tomate',
      'Bohnen',
      'Kohlrabi',
      'Kohl',
      'Schwarzwurzel',
      'Rhabarber',
      'Dill',
      'Radieschen',
      'Rettich',
      'Salatgurke',
      'Fenchel',
      'Erdbeere',
      'Erbse',
      'Pfefferminze',
      'Zuckermais',
      'Lauch',
    ],
    bad: ['Petersilie'],
    color: '#9ccc65',
    icon: 'kopfsalat',
  },
  {
    id: '01M49THV00Z72B8W8Z7M1NQ23N',
    name: 'Kürbis',
    category: 'GEMUESE',
    family: 'Kürbisgewächse',
    feeder: 'STARK',
    spacingInRowCm: 150,
    rowSpacingCm: 150,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 20 },
    good: ['Bohnen', 'Zuckermais', 'Kohlrabi', 'Erbse', 'Zwiebel'],
    bad: ['Salatgurke', 'Tomate'],
    color: '#e67e22',
    icon: 'kuerbis',
  },
  {
    id: '01M49THV00BS8T7Z8ZDSW03PXH',
    name: 'Lauch',
    category: 'GEMUESE',
    family: 'Lauchgewächse',
    feeder: 'STARK',
    spacingInRowCm: 15,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 22 },
    good: [
      'Tomate',
      'Sellerie',
      'Schwarzwurzel',
      'Kopfsalat',
      'Kohlrabi',
      'Kohl',
      'Möhre',
      'Endivie',
      'Erdbeere',
    ],
    bad: ['Bohnen', 'Erbse', 'Rote Bete'],
    color: '#5f8d4e',
    icon: 'lauch',
  },
  {
    id: '01M49THV00PAF8V0RQKEJ6T6FT',
    name: 'Mangold',
    category: 'GEMUESE',
    family: 'Fuchsschwanzgewächse',
    feeder: 'MITTEL',
    spacingInRowCm: 30,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 20 },
    good: ['Radieschen', 'Rettich', 'Kohl', 'Möhre', 'Buschbohne'],
    bad: [],
    color: '#d84f6b',
    icon: 'mangold',
  },
  {
    id: '01M49THV0022SSWEDY081PHP6T',
    name: 'Möhre',
    category: 'GEMUESE',
    family: 'Doldenblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 4,
    rowSpacingCm: 25,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 14 },
    good: [
      'Zwiebel',
      'Endivie',
      'Radicchio',
      'Tomate',
      'Schwarzwurzel',
      'Erbse',
      'Dill',
      'Lauch',
      'Knoblauch',
      'Radieschen',
      'Rettich',
      'Mangold',
    ],
    bad: [],
    color: '#f08a24',
    icon: 'moehre',
  },
  {
    id: '01M49THV00C3EM81MSEDXQCJ8S',
    name: 'Paprika',
    category: 'GEMUESE',
    family: 'Nachtschattengewächse',
    feeder: 'STARK',
    spacingInRowCm: 40,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 18 },
    good: ['Möhre', 'Zwiebel', 'Lauch', 'Salatgurke', 'Erdbeere'],
    bad: ['Fenchel'],
    color: '#e53935',
    icon: 'paprika',
  },
  {
    id: '01M49THV00BZG7SJEJJ53J7Q3D',
    name: 'Pastinake',
    category: 'GEMUESE',
    family: 'Doldenblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 20,
    rowSpacingCm: 35,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 30 },
    good: [],
    bad: [],
    color: '#e6d7a8',
    icon: 'pastinake',
  },
  {
    id: '01M49THV00K1R589BR0NCZ99WJ',
    name: 'Pflücksalat',
    category: 'GEMUESE',
    family: 'Korbblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 35,
    rowSpacingCm: 35,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 10 },
    good: [
      'Tomate',
      'Schwarzwurzel',
      'Rhabarber',
      'Rote Bete',
      'Radieschen',
      'Rettich',
      'Kohl',
      'Fenchel',
      'Dill',
      'Buschbohne',
    ],
    bad: [],
    color: '#8fbf4d',
    icon: 'pfluecksalat',
  },
  {
    id: '01M49THV00X3V29ZBZ80HY60X8',
    name: 'Radicchio',
    category: 'GEMUESE',
    family: 'Korbblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 20,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: ['Tomate', 'Stangenbohne', 'Kopfsalat', 'Möhre', 'Fenchel'],
    bad: [],
    color: '#8e2449',
    icon: 'radicchio',
  },
  {
    id: '01M49THV00NAC3VGAMQF7XGNWF',
    name: 'Radieschen',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 5,
    rowSpacingCm: 10,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 5 },
    good: [
      'Tomate',
      'Bohnen',
      'Spinat',
      'Pflücksalat',
      'Petersilie',
      'Mangold',
      'Kopfsalat',
      'Kohl',
      'Möhre',
      'Kohlrabi',
      'Kapuzinerkresse',
      'Erdbeere',
      'Erbse',
    ],
    bad: ['Salatgurke'],
    color: '#e84a6f',
    icon: 'radieschen',
  },
  {
    id: '01M49THV005NN12JCEESTHTR2P',
    name: 'Rettich',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 15,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 9 },
    good: { like: 'Radieschen' },
    bad: { like: 'Radieschen' },
    color: '#f1ece0',
    icon: 'rettich',
  },
  {
    id: '01M49THV00NV0NBQGTEVXR8QFM',
    name: 'Rhabarber',
    category: 'GEMUESE',
    family: 'Knöterichgewächse',
    feeder: 'STARK',
    spacingInRowCm: 120,
    rowSpacingCm: 120,
    lifecycle: { type: 'PERENNIAL' },
    good: ['Spinat', 'Pflücksalat', 'Kopfsalat', 'Kohl', 'Buschbohne'],
    bad: [],
    color: '#b5304a',
    icon: 'rhabarber',
  },
  {
    id: '01M49THV004N4PPK203E742ZD0',
    name: 'Rosenkohl',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'STARK',
    spacingInRowCm: 60,
    rowSpacingCm: 60,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 30 },
    good: { like: 'Brokkoli' },
    bad: { like: 'Brokkoli' },
    color: '#3d7a3a',
    icon: 'rosenkohl',
  },
  {
    id: '01M49THV007QZ49TY1XCYCQ54J',
    name: 'Rote Bete',
    category: 'GEMUESE',
    family: 'Fuchsschwanzgewächse',
    feeder: 'MITTEL',
    spacingInRowCm: 10,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 14 },
    good: [
      'Zwiebel',
      'Pflücksalat',
      'Kohlrabi',
      'Knoblauch',
      'Salatgurke',
      'Erdbeere',
      'Dill',
      'Buschbohne',
    ],
    bad: ['Zuckermais', 'Lauch', 'Kartoffel'],
    color: '#8b1e3f',
    icon: 'rote-bete',
  },
  {
    id: '01M49THV00HR6QE9NHPBZ5EQZ7',
    name: 'Rotkohl',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'STARK',
    spacingInRowCm: 50,
    rowSpacingCm: 60,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 20 },
    good: { like: 'Brokkoli' },
    bad: { like: 'Brokkoli' },
    color: '#6a2c70',
    icon: 'rotkohl',
  },
  {
    id: '01M49THV00J20MTCN11XHWM3TX',
    name: 'Rucola',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 3,
    rowSpacingCm: 20,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 6 },
    good: [],
    bad: [],
    color: '#557a2e',
    icon: 'rucola',
  },
  {
    id: '01M49THV00YXGE5D995DD6M16J',
    name: 'Salatgurke',
    category: 'GEMUESE',
    family: 'Kürbisgewächse',
    feeder: 'STARK',
    spacingInRowCm: 40,
    rowSpacingCm: 100,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: [
      'Zwiebel',
      'Bohnen',
      'Sellerie',
      'Rote Bete',
      'Kopfsalat',
      'Kohl',
      'Knoblauch',
      'Dill',
      'Fenchel',
    ],
    bad: ['Radieschen', 'Rettich'],
    color: '#3e8e41',
    icon: 'salatgurke',
  },
  {
    id: '01M49THV00KSPK51CR27YYPVT6',
    name: 'Schwarzwurzel',
    category: 'GEMUESE',
    family: 'Korbblütler',
    feeder: 'MITTEL',
    spacingInRowCm: 10,
    rowSpacingCm: 25,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 30 },
    good: ['Zwiebel', 'Pflücksalat', 'Lauch', 'Kopfsalat', 'Kohlrabi', 'Möhre'],
    bad: [],
    color: '#4a3b2a',
    icon: 'schwarzwurzel',
  },
  {
    id: '01M49THV009C9ACEM9APGSMT4E',
    name: 'Spinat',
    category: 'GEMUESE',
    family: 'Fuchsschwanzgewächse',
    feeder: 'MITTEL',
    spacingInRowCm: 10,
    rowSpacingCm: 15,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 8 },
    good: [
      'Tomate',
      'Stangenbohne',
      'Sellerie',
      'Rhabarber',
      'Radieschen',
      'Rettich',
      'Kohlrabi',
      'Kohl',
      'Kartoffel',
      'Erdbeere',
    ],
    bad: ['Rote Bete', 'Mangold'],
    color: '#2e7d32',
    icon: 'spinat',
  },
  {
    id: '01M49THV00J0CZ15EY7VAY4QBN',
    name: 'Stangenbohne',
    category: 'GEMUESE',
    family: 'Hülsenfrüchtler',
    feeder: 'SCHWACH',
    spacingInRowCm: 80,
    rowSpacingCm: 80,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: [
      'Zucchini',
      'Endivie',
      'Radicchio',
      'Spinat',
      'Sellerie',
      'Radieschen',
      'Rettich',
      'Kopfsalat',
      'Kohlrabi',
      'Kohl',
      'Kapuzinerkresse',
      'Salatgurke',
    ],
    bad: ['Zwiebel', 'Lauch', 'Knoblauch', 'Fenchel', 'Erbse'],
    color: '#558b2f',
    icon: 'stangenbohne',
  },
  {
    id: '01M49THV00QAJ0PW1HJJ512ESK',
    name: 'Staudensellerie',
    category: 'GEMUESE',
    family: 'Doldenblütler',
    feeder: 'STARK',
    spacingInRowCm: 40,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 18 },
    good: { like: 'Knollensellerie' },
    bad: { like: 'Knollensellerie' },
    color: '#8fb35a',
    icon: 'staudensellerie',
  },
  {
    id: '01M49THV00QS1SEJEM64991JH5',
    name: 'Tomate',
    category: 'GEMUESE',
    family: 'Nachtschattengewächse',
    feeder: 'STARK',
    spacingInRowCm: 60,
    rowSpacingCm: 60,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 22 },
    good: [
      'Radicchio',
      'Spinat',
      'Sellerie',
      'Radieschen',
      'Rettich',
      'Pflücksalat',
      'Pfefferminze',
      'Petersilie',
      'Kopfsalat',
      'Kohlrabi',
      'Kohl',
      'Knoblauch',
      'Möhre',
      'Buschbohne',
      'Lauch',
    ],
    bad: ['Kartoffel', 'Fenchel', 'Erbse'],
    color: '#d32f2f',
    icon: 'tomate',
  },
  {
    id: '01M49THV00SG53SSSYR0V8PXP9',
    name: 'Weißkohl',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'STARK',
    spacingInRowCm: 50,
    rowSpacingCm: 60,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 20 },
    good: { like: 'Brokkoli' },
    bad: { like: 'Brokkoli' },
    color: '#cfe0b4',
    icon: 'weisskohl',
  },
  {
    id: '01M49THV009ZDBFTFH56KZXNNH',
    name: 'Wirsing',
    category: 'GEMUESE',
    family: 'Kreuzblütler',
    feeder: 'STARK',
    spacingInRowCm: 50,
    rowSpacingCm: 50,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 18 },
    good: { like: 'Brokkoli' },
    bad: { like: 'Brokkoli' },
    color: '#7fa55a',
    icon: 'wirsing',
  },
  {
    id: '01M49THV00VCY3FS4DV6YYZ4KH',
    name: 'Zucchini',
    category: 'GEMUESE',
    family: 'Kürbisgewächse',
    feeder: 'STARK',
    spacingInRowCm: 100,
    rowSpacingCm: 100,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 18 },
    good: ['Zwiebel', 'Stangenbohne'],
    bad: [],
    color: '#33691e',
    icon: 'zucchini',
  },
  {
    id: '01M49THV00QJW5HP6E8A6A5DSX',
    name: 'Zuckermais',
    category: 'GEMUESE',
    family: 'Süßgräser',
    feeder: 'STARK',
    spacingInRowCm: 30,
    rowSpacingCm: 40,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: ['Kopfsalat', 'Kürbis', 'Salatgurke', 'Kartoffel'],
    bad: ['Sellerie', 'Rote Bete', 'Tomate'],
    color: '#f4c430',
    icon: 'zuckermais',
  },
  {
    id: '01M49THV006G34Z07ZJ8N4X0KS',
    name: 'Zwiebel',
    category: 'GEMUESE',
    family: 'Lauchgewächse',
    feeder: 'SCHWACH',
    spacingInRowCm: 10,
    rowSpacingCm: 25,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 18 },
    good: [
      'Zucchini',
      'Schwarzwurzel',
      'Rote Bete',
      'Dill',
      'Salatgurke',
      'Kopfsalat',
      'Möhre',
      'Erdbeere',
    ],
    bad: ['Bohnen', 'Kohl'],
    color: '#c9a227',
    icon: 'zwiebel',
  },
  {
    id: '01M49THV00W40ZTZ5PDDE1E2S8',
    name: 'Erdbeere',
    category: 'OBST',
    family: 'Rosengewächse',
    feeder: 'MITTEL',
    spacingInRowCm: 30,
    rowSpacingCm: 90,
    lifecycle: { type: 'MULTI_YEAR', years: 3 },
    good: [
      'Radieschen',
      'Rettich',
      'Rote Bete',
      'Petersilie',
      'Lauch',
      'Knoblauch',
      'Buschbohne',
      'Kopfsalat',
      'Zwiebel',
      'Spinat',
    ],
    bad: ['Kohl', 'Kartoffel', 'Tomate'],
    color: '#e0245e',
    icon: 'erdbeere',
  },
  {
    id: '01M49THV0081S9TVW6N7P7AW3Q',
    name: 'Basilikum',
    category: 'KRAUT',
    family: 'Lippenblütler',
    feeder: 'STARK',
    spacingInRowCm: 25,
    rowSpacingCm: 25,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: [],
    bad: [],
    color: '#43a047',
    icon: 'basilikum',
  },
  {
    id: '01M49THV00JZTDDVAKN2ZQ7JK7',
    name: 'Bohnenkraut',
    category: 'KRAUT',
    family: 'Lippenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 25,
    rowSpacingCm: 25,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 16 },
    good: [],
    bad: [],
    color: '#7d9a5b',
    icon: 'bohnenkraut',
  },
  {
    id: '01M49THV00265C6MX9XK8KAB05',
    name: 'Dill',
    category: 'KRAUT',
    family: 'Doldenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 30,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 10 },
    good: ['Zwiebel', 'Rote Bete', 'Pflücksalat', 'Möhre', 'Salatgurke', 'Erbse', 'Kopfsalat'],
    bad: ['Fenchel', 'Koriander'],
    color: '#a5c95b',
    icon: 'dill',
  },
  {
    id: '01M49THV003V746TJ52CT0AYAQ',
    name: 'Kapuzinerkresse',
    category: 'KRAUT',
    family: 'Kapuzinerkressengewächse',
    feeder: 'SCHWACH',
    spacingInRowCm: 10,
    rowSpacingCm: 20,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 20 },
    good: ['Stangenbohne', 'Radieschen', 'Rettich'],
    bad: [],
    color: '#f57c00',
    icon: 'kapuzinerkresse',
  },
  {
    id: '01M49THV00TBZN5BN2CBZ3YWBS',
    name: 'Koriander',
    category: 'KRAUT',
    family: 'Doldenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 15,
    rowSpacingCm: 30,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 10 },
    good: [],
    bad: ['Dill'],
    color: '#6b9e3f',
    icon: 'koriander',
  },
  {
    id: '01M49THV00P626ZHHDF4957HH7',
    name: 'Oregano',
    category: 'KRAUT',
    family: 'Lippenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 15,
    rowSpacingCm: 20,
    lifecycle: { type: 'PERENNIAL' },
    good: [],
    bad: [],
    color: '#6d8b4a',
    icon: 'oregano',
  },
  {
    id: '01M49THV00W2T9ZJHHDX8H5YMY',
    name: 'Petersilie',
    category: 'KRAUT',
    family: 'Doldenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 5,
    rowSpacingCm: 20,
    lifecycle: { type: 'ANNUAL', cultureWeeks: 30 },
    good: ['Tomate', 'Radieschen', 'Rettich', 'Erdbeere'],
    bad: ['Kopfsalat'],
    color: '#388e3c',
    icon: 'petersilie',
  },
  {
    id: '01M49THV00K0MBAQQYD01X2GTX',
    name: 'Pfefferminze',
    category: 'KRAUT',
    family: 'Lippenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 30,
    rowSpacingCm: 30,
    lifecycle: { type: 'PERENNIAL' },
    good: ['Tomate', 'Kopfsalat', 'Möhre', 'Kartoffel'],
    bad: [],
    color: '#26a69a',
    icon: 'pfefferminze',
  },
  {
    id: '01M49THV0088BETVBD9HZY3BH3',
    name: 'Rosmarin',
    category: 'KRAUT',
    family: 'Lippenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 50,
    rowSpacingCm: 50,
    lifecycle: { type: 'PERENNIAL' },
    good: [],
    bad: [],
    color: '#5c7c6a',
    icon: 'rosmarin',
  },
  {
    id: '01M49THV00D1ZZTRW7KBQT1ZGN',
    name: 'Salbei',
    category: 'KRAUT',
    family: 'Lippenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 40,
    rowSpacingCm: 30,
    lifecycle: { type: 'PERENNIAL' },
    good: ['Fenchel'],
    bad: [],
    color: '#8aa39b',
    icon: 'salbei',
  },
  {
    id: '01M49THV00JTGP22ZW0RKZZT9K',
    name: 'Schnittlauch',
    category: 'KRAUT',
    family: 'Lauchgewächse',
    feeder: 'SCHWACH',
    spacingInRowCm: 20,
    rowSpacingCm: 25,
    lifecycle: { type: 'PERENNIAL' },
    good: [],
    bad: [],
    color: '#7e57c2',
    icon: 'schnittlauch',
  },
  {
    id: '01M49THV00Y146B7QH3XHMRCBA',
    name: 'Thymian',
    category: 'KRAUT',
    family: 'Lippenblütler',
    feeder: 'SCHWACH',
    spacingInRowCm: 20,
    rowSpacingCm: 20,
    lifecycle: { type: 'PERENNIAL' },
    good: [],
    bad: [],
    color: '#90a17b',
    icon: 'thymian',
  },
];
